// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBdXRigs9juW5T7eK_4s49Im5deob1fJc',
    appId: '1:733014771219:web:907ce14da06cf087f9a1e6',
    messagingSenderId: '733014771219',
    projectId: 'othello-94686',
    authDomain: 'othello-94686.firebaseapp.com',
    storageBucket: 'othello-94686.firebasestorage.app',
    measurementId: 'G-YEJ06CK8KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4uVDXNu89GExfEWpD7131h3yAMhnjdLE',
    appId: '1:733014771219:android:c750d7cde13d0a78f9a1e6',
    messagingSenderId: '733014771219',
    projectId: 'othello-94686',
    storageBucket: 'othello-94686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4iaE25zcboXTU_j19SuLg0f7ubKqUpAs',
    appId: '1:733014771219:ios:4fc21c9247537a0ef9a1e6',
    messagingSenderId: '733014771219',
    projectId: 'othello-94686',
    storageBucket: 'othello-94686.firebasestorage.app',
    androidClientId: '733014771219-h47n93teaamqje1uobooma5b52vcabgv.apps.googleusercontent.com',
    iosClientId: '733014771219-g1mvd1jpt2k1uootuhoo29sagj1rhh20.apps.googleusercontent.com',
    iosBundleId: 'com.vishnuworld.othello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4iaE25zcboXTU_j19SuLg0f7ubKqUpAs',
    appId: '1:733014771219:ios:4fc21c9247537a0ef9a1e6',
    messagingSenderId: '733014771219',
    projectId: 'othello-94686',
    storageBucket: 'othello-94686.firebasestorage.app',
    androidClientId: '733014771219-h47n93teaamqje1uobooma5b52vcabgv.apps.googleusercontent.com',
    iosClientId: '733014771219-g1mvd1jpt2k1uootuhoo29sagj1rhh20.apps.googleusercontent.com',
    iosBundleId: 'com.vishnuworld.othello',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwRYp4omJU0-n8m2oN8w_MSraNgugKeOI',
    appId: '1:733014771219:web:079df0d931a5b379f9a1e6',
    messagingSenderId: '733014771219',
    projectId: 'othello-94686',
    authDomain: 'othello-94686.firebaseapp.com',
    storageBucket: 'othello-94686.firebasestorage.app',
    measurementId: 'G-14W2K3D0NB',
  );
}
